package ca.uhnresearch.pughlab.tracker.dao;

/**
 * This represents an object that is generated by the StudyRepository to
 * select a set of cases, usually starting with the whole of a study.
 * 
 * @author stuartw
 */
public interface StudyCaseQuery {

}
