SET SESSION SQL_MODE = 'ansi,strict_all_tables,no_auto_value_on_zero';

DELETE FROM "CASE_ATTRIBUTE_STRINGS" WHERE "ATTRIBUTE_ID" = 0;
DELETE FROM "CASE_ATTRIBUTE_BOOLEANS" WHERE "ATTRIBUTE_ID" = 0;
DELETE FROM "CASE_ATTRIBUTE_DATES" WHERE "ATTRIBUTE_ID" = 0;
DELETE FROM "CASE_ATTRIBUTE_NUMBERS" WHERE "ATTRIBUTE_ID" = 0;

-- Clean duplicates from CASE_ATTRIBUTE_STRINGS
CREATE TEMPORARY TABLE "RECENT_IDS"
SELECT MAX("ID") AS "ID"
FROM "CASE_ATTRIBUTE_STRINGS" 
GROUP BY "CASE_ID", "ATTRIBUTE_ID";

CREATE INDEX "RECENT_IDS_IDX" ON "RECENT_IDS"("ID");

DELETE FROM "CASE_ATTRIBUTE_STRINGS"
WHERE "ID" NOT IN (SELECT "ID" FROM "RECENT_IDS");

DROP TEMPORARY TABLE "RECENT_IDS";


-- Clean duplicates from CASE_ATTRIBUTE_BOOLEANS
CREATE TEMPORARY TABLE "RECENT_IDS"
SELECT MAX("ID") AS "ID"
FROM "CASE_ATTRIBUTE_BOOLEANS" 
GROUP BY "CASE_ID", "ATTRIBUTE_ID";

CREATE INDEX "RECENT_IDS_IDX" ON "RECENT_IDS"("ID");

DELETE FROM "CASE_ATTRIBUTE_BOOLEANS"
WHERE "ID" NOT IN (SELECT "ID" FROM "RECENT_IDS");

DROP TEMPORARY TABLE "RECENT_IDS";


-- Clean duplicates from CASE_ATTRIBUTE_DATES
CREATE TEMPORARY TABLE "RECENT_IDS"
SELECT MAX("ID") AS "ID"
FROM "CASE_ATTRIBUTE_DATES" 
GROUP BY "CASE_ID", "ATTRIBUTE_ID";

CREATE INDEX "RECENT_IDS_IDX" ON "RECENT_IDS"("ID");

DELETE FROM "CASE_ATTRIBUTE_DATES"
WHERE "ID" NOT IN (SELECT "ID" FROM "RECENT_IDS");

DROP TEMPORARY TABLE "RECENT_IDS";


-- Clean duplicates from CASE_ATTRIBUTE_NUMBERS
CREATE TEMPORARY TABLE "RECENT_IDS"
SELECT MAX("ID") AS "ID"
FROM "CASE_ATTRIBUTE_NUMBERS" 
GROUP BY "CASE_ID", "ATTRIBUTE_ID";

CREATE INDEX "RECENT_IDS_IDX" ON "RECENT_IDS"("ID");

DELETE FROM "CASE_ATTRIBUTE_NUMBERS"
WHERE "ID" NOT IN (SELECT "ID" FROM "RECENT_IDS");

DROP TEMPORARY TABLE "RECENT_IDS";

CREATE TEMPORARY TABLE "RECENT_IDS"
SELECT VA.*
FROM "VIEW_ATTRIBUTES" VA
LEFT JOIN "ATTRIBUTES" A ON VA."ATTRIBUTE_ID" = A."ID"
WHERE A."ID" IS NULL;

DELETE "VIEW_ATTRIBUTES"
FROM "VIEW_ATTRIBUTES"
JOIN "RECENT_IDS" 
ON "RECENT_IDS"."VIEW_ID" = "VIEW_ATTRIBUTES"."VIEW_ID" 
AND "RECENT_IDS"."ATTRIBUTE_ID" = "VIEW_ATTRIBUTES"."ATTRIBUTE_ID";

DROP TEMPORARY TABLE "RECENT_IDS";

-- Get the primary keys right
ALTER TABLE "STUDIES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "ATTRIBUTES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "VIEWS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "AUDIT_LOG" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "CASE_ATTRIBUTE_STRINGS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "CASE_ATTRIBUTE_BOOLEANS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "CASE_ATTRIBUTE_DATES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "CASE_ATTRIBUTE_NUMBERS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "CASES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "ROLE_PERMISSIONS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "USER_ROLES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "ROLES" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE "USERS" MODIFY COLUMN "ID" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;


-- And add referential integrity
ALTER TABLE "ATTRIBUTES"
MODIFY COLUMN "STUDY_ID" INT(11) UNSIGNED NOT NULL,
ADD INDEX ("STUDY_ID"),
ADD CONSTRAINT "ATTRIBUTES_STUDY_ID_IDX" FOREIGN KEY "ATTRIBUTES_STUDY_ID_KEY" ("STUDY_ID") REFERENCES "STUDIES"("ID");

ALTER TABLE "VIEWS"
MODIFY COLUMN "STUDY_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "VIEWS_STUDY_ID_IDX" FOREIGN KEY "VIEWS_STUDY_ID_KEY" ("STUDY_ID") REFERENCES "STUDIES"("ID");

ALTER TABLE "VIEW_ATTRIBUTES"
MODIFY COLUMN "VIEW_ID" INT(11) UNSIGNED NOT NULL,
MODIFY COLUMN "ATTRIBUTE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "VIEW_ATTRIBUTES_VIEW_ID_IDX" FOREIGN KEY "VIEW_ATTRIBUTES_VIEW_ID_KEY" ("VIEW_ID") REFERENCES "VIEWS"("ID"),
ADD CONSTRAINT "VIEW_ATTRIBUTES_ATTRIBUTE_ID_IDX" FOREIGN KEY "VIEW_ATTRIBUTES_ATTRIBUTE_ID_KEY" ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTES"("ID");

ALTER TABLE "CASES"
MODIFY COLUMN "STUDY_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "CASES_STUDY_ID_IDX" FOREIGN KEY "CASES_STUDY_ID_KEY" ("STUDY_ID") REFERENCES "STUDIES"("ID");

ALTER TABLE "CASE_ATTRIBUTE_STRINGS"
MODIFY COLUMN "CASE_ID" INT(11) UNSIGNED NOT NULL,
MODIFY COLUMN "ATTRIBUTE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "CASE_ATTRIBUTE_STRINGS_CASE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_STRINGS_CASE_ID_IDX" ("CASE_ID") REFERENCES "CASES"("ID"),
ADD CONSTRAINT "CASE_ATTRIBUTE_STRINGS_ATTRIBUTE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_STRINGS_ATTRIBUTE_ID_IDX" ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTES"("ID");

ALTER TABLE "CASE_ATTRIBUTE_BOOLEANS"
MODIFY COLUMN "CASE_ID" INT(11) UNSIGNED NOT NULL,
MODIFY COLUMN "ATTRIBUTE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "CASE_ATTRIBUTE_BOOLEANS_CASE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_BOOLEANS_CASE_ID_IDX" ("CASE_ID") REFERENCES "CASES"("ID"),
ADD CONSTRAINT "CASE_ATTRIBUTE_BOOLEANS_ATTRIBUTE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_BOOLEANS_ATTRIBUTE_ID_IDX" ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTES"("ID");

ALTER TABLE "CASE_ATTRIBUTE_DATES"
MODIFY COLUMN "CASE_ID" INT(11) UNSIGNED NOT NULL,
MODIFY COLUMN "ATTRIBUTE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "CASE_ATTRIBUTE_DATES_CASE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_DATES_CASE_ID_IDX" ("CASE_ID") REFERENCES "CASES"("ID"),
ADD CONSTRAINT "CASE_ATTRIBUTE_DATES_ATTRIBUTE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_DATES_ATTRIBUTE_ID_IDX" ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTES"("ID");

ALTER TABLE "CASE_ATTRIBUTE_NUMBERS"
MODIFY COLUMN "CASE_ID" INT(11) UNSIGNED NOT NULL,
MODIFY COLUMN "ATTRIBUTE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "CASE_ATTRIBUTE_NUMBERS_CASE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_NUMBERS_CASE_ID_IDX" ("CASE_ID") REFERENCES "CASES"("ID"),
ADD CONSTRAINT "CASE_ATTRIBUTE_NUMBERS_ATTRIBUTE_ID_IDX" FOREIGN KEY "CASE_ATTRIBUTE_NUMBERS_ATTRIBUTE_ID_IDX" ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTES"("ID");

ALTER TABLE "ROLES"
MODIFY COLUMN "STUDY_ID" INT(11) UNSIGNED,
ADD CONSTRAINT "ROLES_STUDY_ID_IDX" FOREIGN KEY "ROLES_STUDY_ID_KEY" ("STUDY_ID") REFERENCES "STUDIES"("ID");

ALTER TABLE "USER_ROLES"
MODIFY COLUMN "ROLE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "USER_ROLES_ROLE_ID_IDX" FOREIGN KEY "USER_ROLES_ROLE_ID_KEY" ("ROLE_ID") REFERENCES "ROLES"("ID");

ALTER TABLE "ROLE_PERMISSIONS"
MODIFY COLUMN "ROLE_ID" INT(11) UNSIGNED NOT NULL,
ADD CONSTRAINT "ROLE_PERMISSIONS_ROLE_ID_IDX" FOREIGN KEY "ROLE_PERMISSIONS_ROLE_ID_KEY" ("ROLE_ID") REFERENCES "ROLES"("ID");
